WIP: Change NodeID to NodeKey
synnaxlabs/synnax pull request #236
Opened 2023-03-11 23:11 UTC by zeina1i

2023-03-28 20:38 UTC, zeina1i commented
Hey @emilbon99

Client Test / test-typescript and Freighter Test / build-integration-image pipelines are failed.
But the weird thing is that when I trigger them in my local I don't have these errors. Do you have any idea?

2023-03-28 20:44 UTC, emilbon99 commented
> Hey @emilbon99
> 
> Client Test / test-typescript and Freighter Test / build-integration-image pipelines are failed. But the weird thing is that when I trigger them in my local I don't have these errors. Do you have any idea?

I'll debug. Give me an hour or two.

2023-03-28 21:04 UTC, emilbon99 commented
@zeina1i Issue fixed, just had to update the go mod file. The freighter tests aren't passing because PR's from forks don't have access to github packages. The client tests are failing because it's using the current production build of Synnax, which doesn't have your changes yet (I need to fix this :). What we can do for now is merge this PR into a separate branch on the main repo, make sure all CI passes, and then we should be good to go. Does that sound good?

2023-03-28 21:37 UTC, zeina1i commented
@emilbon99 yes,
That sounds great👍

Should I do an action for that? Or you would do it?

2023-03-28 22:26 UTC, emilbon99 commented
I'll get it done.

2023-03-30 16:50 UTC, emilbon99 requested changes
Thank you for doing all of this busy work! Aside from a few argument names that need to be changed and some RFC changes to rollback it looks great. Let me know when you've made these and we can get it merged into the main repo for CI.

2023-03-30 16:50 UTC, emilbon99 commented on aspen/internal/cluster/cluster.go
> +	Resolve(id node.Key) (address.Address, error)
Can we change the `id` arg name to `key` as well?

2023-03-30 16:50 UTC, emilbon99 commented on aspen/internal/cluster/cluster.go
> +func (c *cluster) Node(id node.Key) (node.Node, error) {
See above. `id` -> `key`

2023-03-30 16:50 UTC, emilbon99 commented on aspen/internal/cluster/cluster.go
> +func (c *cluster) Resolve(id node.Key) (address.Address, error) {
`id` -> `key`

2023-03-30 16:50 UTC, emilbon99 commented on aspen/internal/cluster/pledge/pledge.go
> +func (r *responsible) consultQuorum(ctx context.Context, id node.Key, quorum node.Group) error {
`id` -> `key`

2023-03-30 16:50 UTC, emilbon99 commented on aspen/internal/cluster/pledge/pledge_test.go
> +								return nodes.Where(func(id node.Key, _ node.Node) bool {
`id` -> `key`

2023-03-30 16:50 UTC, emilbon99 commented on aspen/internal/cluster/store/store.go
> +func (c *core) GetNode(id node.Key) (node.Node, bool) {
`id` -> `key`

2023-03-30 16:50 UTC, emilbon99 commented on aspen/internal/node/group.go
> +	return n.Where(func(id Key, _ Node) bool { return lo.Count(ids, id) == 0 })
`id` -> `key`

2023-03-30 16:50 UTC, emilbon99 commented on aspen/internal/node/group.go
> +func (n Group) WhereNot(ids ...Key) Group {
`ids` -> `keys`

2023-03-30 16:50 UTC, emilbon99 commented on aspen/internal/node/node.go
> +func (i Key) Parse(str string) (Key, error) {
`i` -> `k`

2023-03-30 16:50 UTC, emilbon99 commented on docs/rfc/2-220518-aspen-distributed-storage.mdx
I generally like to keep RFCs frozen after they are completed to preserve a record of iteration. I think we should keep the term node ID in this RFC and instead add a section noting the change. What do you think?

2023-03-30 16:50 UTC, emilbon99 commented on docs/rfc/3-220604-segment-distribution.mdx
See my comment on RFC 2.

2023-03-30 16:50 UTC, emilbon99 commented on docs/rfc/5-220716-ontology.mdx
The `ID` referenced in this RFC is unrelated to nodes. It should remain as `ID`.

2023-03-30 16:50 UTC, emilbon99 commented on synnax/pkg/distribution/channel/channel.go
> +	NodeKey, err := strconv.Atoi(split[0])
This should be camel case

2023-03-30 16:50 UTC, emilbon99 commented on synnax/pkg/distribution/core/ontology.go
> +	schema.Set(e, "id", uint32(n.Key))
`id` -> `key`

2023-03-30 16:50 UTC, emilbon99 commented on synnax/pkg/distribution/framer/writer/service.go
> +		hostID             = s.HostResolver.HostKey()
`hostID` -> `hostKey`

2023-04-02 16:27 UTC, zeina1i commented on docs/rfc/2-220518-aspen-distributed-storage.mdx
I agree with you.
What do you think if we have an expand button infront of the part that we are intending the edit and when we click on expand a section would be opened which contains these items:
(in our case)
**original text**
Node.ID
**corrected text**
Node.Key
**notes**
A Node's ID uint32 ID is only unique to its subtype, and is not universally unique. So we rename Node.ID to Node.Key.


(If we don't have the expand button at the moment, We can also use an internal link to the "updates" section in the bottom of the page, but comparing to "expand button" it has the downside of the user has to return back to the original text after reading the updated section.)

Which one do you prefer?

2023-04-02 16:27 UTC, zeina1i commented on docs/rfc/3-220604-segment-distribution.mdx
See my comment on RFC 2 :)

2023-04-02 16:29 UTC, zeina1i commented on docs/rfc/2-220518-aspen-distributed-storage.mdx
Bytheway at the moment I rolledback the rfcs to their original version.
And we can proceed when we finalize our discusstion on how the update parts should be shown in the rfcs.

2023-04-02 16:34 UTC, zeina1i commented
> Thank you for doing all of this busy work! Aside from a few argument names that need to be changed and some RFC changes to rollback it looks great. Let me know when you've made these and we can get it merged into the main repo for CI.

Thanks @emilbon99 
I resolved the namings.
And waiting on your opinion about the suggestions I had on the [rfcs](https://github.com/synnaxlabs/synnax/pull/236#discussion_r1155340233), Then I would do rfc changes as well.

2023-04-03 20:07 UTC, emilbon99 commented
@zeina1i I like the idea of adding a tooltip. I'll add that as another issue we can work in the future. Leaving the exiting version is fine for now.

2023-04-03 20:15 UTC, zeina1i commented
@emilbon99 Good :),  so, then should I resolve the rfc discussions in this state?

2023-04-11 15:14 UTC, merged