[deployer] - Impl Synnax Deployer, resolves #355
synnaxlabs/synnax pull request #358
Opened 2023-09-19 22:55 UTC by MatchaOnMuffins

This PR addresses issue #355 by providing a Docker-based lifecycle management solution to synnax.

2023-09-20 00:32 UTC, emilbon99 requested changes
Two issues to think about.

2023-09-20 00:32 UTC, emilbon99 commented on deploy/deployment.py
> +image_name = "synnaxlabs/synnax"  # image name
Can we make these constants SCREAM_CASE?

2023-09-20 00:32 UTC, emilbon99 commented on deploy/requirements.txt
> +docker
Would it be possible to use poetry here for the virtual environment? Just want to make sure we're standardized across the repo on these things.

2023-09-20 02:53 UTC, MatchaOnMuffins commented
Just resolved the two issues you mentioned. Can you take a look gain?

2023-09-21 02:35 UTC, emilbon99 commented
Hey, sorry I didn't get to this today. Will get to it tomorrow

2023-09-21 14:46 UTC, merged