0016 frame flight protocol
synnaxlabs/synnax pull request #404
Opened 2023-10-10 00:44 UTC by Fazanza

Please leave any comments about the code that u find bad. I will get to as soon as I can. Also will work on the document in the upcoming days

2023-10-11 02:03 UTC, emilbon99 requested changes
Some changes to make. I'd also like to see performance profiling in terms of heap allocation, especially when compared to JSON.

2023-10-11 02:03 UTC, emilbon99 commented on synnax/pkg/distribution/framer/encoder/encoder.go
> +			if index < len(src) && channel.Key(binary.LittleEndian.Uint32(src[index:])) == m.keys[i] {
If statement could be better structured. Just check for the converse and use continue? (or is it inverse). Anyway, you don't need an else statement here.

2023-10-11 02:03 UTC, emilbon99 commented on synnax/pkg/distribution/framer/encoder/encoder_test.go
> +})
I want performance tests!

2023-10-17 02:44 UTC, Fazanza commented on synnax/pkg/distribution/framer/encoder/encoder.go
> +		if index >= len(src.Keys) || src.Keys[index] != m.keys[i] {
The way this is set up, the index will go over the len of the src keys, and was causing an error. Had to implement this condition to stop that.

2023-10-31 14:57 UTC, merged

2023-10-31 14:57 UTC, emilbon99 commented
LGTM