Pjdotson/sy 696 console deep linking: Workspaces, schematics, line plots, ranges
synnaxlabs/synnax pull request #596
Opened 2024-06-01 16:54 UTC by pjdotson

Deep linking implemented for workspaces, schematics, line plots, and ranges.

2024-06-03 14:59 UTC, pjdotson commented on console/src/schematic/link.tsx
> +        // snapshot: schematic.snapshot,
Want to discuss if we should use schematic.snapshot

2024-06-04 20:35 UTC, emilbon99 requested changes

2024-06-04 20:35 UTC, emilbon99 commented on console/src/hardware/task/ontology.tsx
> +      <Ontology.LinkAddressMenuItem />
This seems like it'd be a better fit for the `Link` module instead of the ontology

2024-06-04 20:35 UTC, emilbon99 commented on console/src/layouts/LayoutMain/LayoutMain.tsx
> +  Link.useDeepLink({ handlers: Link.HANDLERS });
Redundant name. Call it `Link.useDeep`

2024-06-04 20:35 UTC, emilbon99 commented on console/src/channel/ontology.tsx
> +      <Ontology.LinkAddressMenuItem />
Would probably be better to make this part of the `Link` package no? Call it `Link.CopyMenuItem`.

2024-06-04 20:35 UTC, emilbon99 commented on console/src/cluster/link.tsx
> +  if (resource !== "cluster") {
I like one-lining these if statements. Feels cleaner -> `if (resource !== "cluster") return false;`

2024-06-04 20:35 UTC, emilbon99 commented on console/src/cluster/link.tsx
> +    console.error(
Dispatch this as a notification instead, so we can give feedback to the user.

2024-06-04 20:35 UTC, emilbon99 commented on console/src/lineplot/link.tsx
> +export const linkHandler: Link.Handler = ({
I would honestly make the link handler be an async function that way we can use the `await` syntax and not `.then`

2024-06-04 20:35 UTC, emilbon99 commented on console/src/lineplot/link.tsx
> +      console.error("Error: ", error);
Dispatch a notification here. I know I don't adhere to this myself but we should be doing it a lot more.

2024-06-04 20:35 UTC, emilbon99 commented on console/src/link/link.tsx
> +export const HANDLERS: Handler[] = [
By importing and specifying all of the handlers here, you're creating a circular dependency. I would think about defining `HANDLERS` elsewhere, such as in `LayoutMain`

2024-06-04 20:35 UTC, emilbon99 commented on console/src/ontology/ContextMenu.tsx
> +export const LinkAddressMenuItem = (): ReactElement => (
Move this to the `Link` module

2024-06-04 20:39 UTC, emilbon99 requested changes

2024-06-04 20:39 UTC, emilbon99 commented on console/src/link/link.tsx
> +    onOpenUrl((urls) => {
Cleanup function here

2024-06-06 17:01 UTC, merged