Leo/sy 685 integration testing
synnaxlabs/synnax pull request #686
Opened 2024-07-04 21:55 UTC by LeonLiur

# Feature Pull Request Template

## Key Information

- [SY-685](https://linear.app/synnaxlabs/issue/SY-685/integration-testing)

## Description

Integration testing framework, integration tests & GitHub actions CI workflow

## Basic Readiness Checklist

- [x] I have performed a self-review of my code.
- [x] I have added relevant tests to cover the changes.
- [x] I have updated user facing documentation accordingly. - **None added**

## Manual QA Additions

- [ ] I have updated the [Release Candidate](/.github/PULL_REQUEST_TEMPLATE/rc.md) template
with necessary manual QA steps to test my change. - **Let's discuss whether the load tests should be part of QA requirements**

## Breaking Changes

Committed `pnpm.lock`, may need particular attention.

2024-07-10 15:09 UTC, emilbon99 requested changes

2024-07-10 16:05 UTC, LeonLiur commented on client/ts/examples/node/liveStream.js
> +    // "stream_write_example_data_1",
You're right, no they don't.

2024-07-13 22:20 UTC, emilbon99 commented on integration/cluster.go
> +	time.Sleep(5 * telem.Second.Duration())
@LeonLiur We should honestly make connectivity check an insecure API that doesn't require authentication

2024-07-13 22:20 UTC, emilbon99 commented on integration/cluster.go
> +	time.Sleep(5 * telem.Second.Duration())
By the way it needs to be a POST request to work

2024-07-13 22:22 UTC, emilbon99 commented on integration/cluster.go
> +	time.Sleep(5 * telem.Second.Duration())
Can you go ahead and make connectivity check an API that doesn't require auth?

2024-07-13 22:59 UTC, Lham42 commented
test-integration failing

2024-07-23 01:08 UTC, Lham42 commented
backmerge main

2024-07-23 01:15 UTC, Lham42 commented on integration/cluster.go
> +	time.Sleep(5 * telem.Second.Duration())
has this been addressed?

2024-07-23 14:51 UTC, LeonLiur commented on integration/cluster.go
> +	time.Sleep(5 * telem.Second.Duration())
Addressed

2024-07-25 00:14 UTC, Lham42 approved these changes
Approve wants you address comments and make note that we will address the integration tests in another linear issue

2024-07-26 15:04 UTC, Lham42 commented
Looks like the synnax test failing was just a flaky test. For any issues you created from this pr - can you also link them in the pr descriptions as issues exposed by these changes?

2024-07-26 18:05 UTC, emilbon99 approved these changes

2024-07-27 03:01 UTC, LeonLiur commented
> Looks like the synnax test failing was just a flaky test. For any issues you created from this pr - can you also link them in the pr descriptions as issues exposed by these changes?

Yes, done

2024-07-27 18:28 UTC, merged