Import / Export Schematics and Line Plots from JSON Files
synnaxlabs/synnax pull request #725
Opened 2024-07-15 01:56 UTC by pjdotson

# Feature Pull Request Template

## Key Information

- **Linear Issue**: [SY-865](https://linear.app/synnaxlabs/issue/SY-865/[console]-import-and-export-schematic-from-json)

## Description

Added the ability to download a schematic and line plot as a JSON file and upload them back into the console.

## Basic Readiness Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have added relevant tests to cover the changes.
- [ ] I have updated user facing documentation accordingly.

## Migrations

- [ ] Console - I have ensured that previous versions of stored data structures are 
properly migrated to new formats.
- [x] Server - I have ensured that previous versions of stored data structures are 
properly migrated to new formats.

## Manual QA Additions

- [ ] I have updated the [Release Candidate](/.github/PULL_REQUEST_TEMPLATE/rc.md) template
with necessary manual QA steps to test my change.

## Breaking Changes

None

2024-07-16 04:25 UTC, emilbon99 requested changes
Looks mostly good. Take a look at my comments.

One major thing we should add . Maybe its in this PR, maybe its in a different one, but you should be able to import a schematic via the command palette

2024-07-16 04:25 UTC, emilbon99 commented on console/src/layouts/Mosaic.tsx
> +      console.log("handleDrop");
A bunch of console logs that need to be removed

2024-07-16 04:25 UTC, emilbon99 commented on console/src/main.tsx
> +  useEffect(() => {
We should extract this into a named hook or add a comment explaining why we put it there.

2024-07-16 04:25 UTC, emilbon99 commented on console/src/schematic/migrations/v2.ts
> +  version: z.literal("2.0.0"),
What about adding a type to differentiate it from a plot?

2024-07-16 04:25 UTC, emilbon99 commented on console/src/schematic/selectors.ts
> +  return useMemoSelect(
Reverse this - doesn't need brackets

2024-07-16 04:25 UTC, emilbon99 commented on console/src/schematic/services/file.ts
> +export const FileHandler: Layout.FileHandler = async ({
Fix case -> `fileHandler`

2024-07-16 04:25 UTC, emilbon99 commented on console/src/schematic/services/file.ts
> +      if (workspaceKey == null) throw Error("Workspace key is required.");
Why throw here? Shouldn't we be able to load a schematic even if there is no active workspace?

2024-07-16 04:25 UTC, emilbon99 commented on console/src/schematic/services/file.ts
> +  dispatch(
You should be able to set the mosaic tab location using the `placer`. There's no need for a separate call to `moveMosaicTab`

2024-07-16 04:25 UTC, emilbon99 commented on console/src/schematic/services/ontology.tsx
> +        state.snapshot = schematic.snapshot;
Should we preserve the snapshot field when exporting schematics? I don't think so.

2024-07-16 04:25 UTC, emilbon99 commented on pluto/src/vis/diagram/edge/connector/connector.ts
> +export const segmentZ = z.object({
If you're going to define a zod type for this, make the segment interface this instead:

`type Segment = z.infer<typeof segmentZ>`

2024-07-16 04:25 UTC, emilbon99 commented on pluto/src/vis/diagram/types.ts
>  export interface Node {
make this a z.infer

2024-07-16 04:25 UTC, emilbon99 commented on pluto/src/vis/diagram/types.ts
>  export interface RFEdgeData {
Make this a z.infer

2024-07-16 04:25 UTC, emilbon99 commented on pluto/src/vis/diagram/types.ts
>  export interface Edge extends RFEdgeData {
Make this a z.infer

2024-07-17 22:36 UTC, Lham42 approved these changes

2024-07-17 22:37 UTC, merged