SY-930 add console tests to ci
synnaxlabs/synnax pull request #756
Opened 2024-08-03 00:09 UTC by Lham42

Please go to the `Preview` tab and select the appropriate template for your pull request.

* [Fix](?expand=1&template=fix.md)
* [Feature](?expand=1&template=feature.md)
* [RC](?expand=1&template=rc.md)

2024-08-03 14:27 UTC, pjdotson commented on console/package.json
> +    "jest": "^29.7.0",
Get rid of this dependency and run `pmpn install` again in root directory.

2024-08-03 14:28 UTC, pjdotson approved these changes
Approved once comment is addressed.

2024-08-06 16:04 UTC, emilbon99 requested changes

2024-08-06 16:04 UTC, emilbon99 commented on .github/workflows/test.console.yaml
This workflow doesn't require us to build the console. You can get rid of most of these statements. I'll mark the ones you can get rid of.

2024-08-07 19:30 UTC, emilbon99 approved these changes
LGTM

2024-08-07 19:36 UTC, merged