New API Generator for TypeScript
synnaxlabs/synnax pull request #757
Opened 2024-08-03 02:02 UTC by pjdotson

2024-08-05 16:13 UTC, Lham42 commented
1.  I think its fine to keep it in the test client
2.  if it is pretty fast I'd add them to the other ts libs
3.  I think causing the checks to fail is probably ideal so we know immediately of we're making api breaking changes

Also can you add to the readme about how togen/view this?

2024-08-06 15:59 UTC, emilbon99 commented
1. I would move this into a separate workflow that only runs when we're merging the RC into main. This workflow should fail if the API is incompatible.
2. No. Pluto is in beta and the other APIs are internal. I don't think it's worth it right now.
3. See #1

2024-08-06 16:01 UTC, emilbon99 requested changes

2024-08-06 18:16 UTC, pjdotson commented
@Lham42 @emilbon99 I'll add a README on how to generate the API in the next commit, but I changed the CI action to only check if the API changes instead of generating it. So development steps would now be:

1. Developer makes a change to the API.
2. Developer runs `genApi:client` in root directory, the `client.api.md` file changes. Push changes to remote branch
3. Changes are viewable in PR, so now reviewers can look at the diffs in the `client.api.md` file.
4. CI runs `checkApi:client`: This only fails if dev didn't do step 2.

2024-08-07 19:53 UTC, merged