Sy 1061 improved meta data for ranges
synnaxlabs/synnax pull request #767
Opened 2024-08-10 17:00 UTC by emilbon99

# Feature Pull Request Template

## Key Information

- **Linear Issue**: [SY-1061](https://linear.app/synnaxlabs/issue/SY-1061/improved-meta-data-for-ranges)

## Description

Improves a number of meta-data related tasks.

## Basic Readiness Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have added relevant tests to cover the changes to CI.
- [ ] I have updated user facing documentation accordingly.
- [ ] I have verified code coverage targets are met.

## Migrations

- [ ] Console - I have ensured that previous versions of stored data structures are 
properly migrated to new formats.
- [ ] Server - I have ensured that previous versions of stored data structures are 
properly migrated to new formats.

##  Additional Notes
- [ ] These changes deal with concurrency.
- [ ] These changes affect UI.

## Manual QA Additions

- [ ] I have updated the [Release Candidate](/.github/PULL_REQUEST_TEMPLATE/rc.md) template
with necessary manual QA steps to test my change.

## Breaking Changes

Please list any breaking changes to public or internal packages.

## Reviwer Checklist
- [ ] Sufficient test coverage of new additions.
- [ ] Verified all steps in the Readiness checklists.
- [ ] UI changes have been tested.
- [ ] Style and formatting is consistent.
- [ ] Reviewed any relevant changes to concurrent code for safety. 
- [ ] Sufficient comments and clarity of code.
- [ ] Any additional documentation necessary for feature is provided and has been reviewed for clarity.

2024-08-12 15:55 UTC, pjdotson reviewed
I'm going to submit this review now so you have a chance to make these changes quickly.

One thought that needs to be added - what happens when we create delete a range that is a parent range of some other ranges? We need to be clear to the user in both client documentation and a console popup that deleting a range will delete all subranges.

2024-08-12 15:55 UTC, pjdotson commented on client/py/examples/load.py
> +
Remove extra empty lines.

2024-08-12 15:55 UTC, pjdotson commented on client/ts/src/ontology/writer.ts
> +import { CrudeID, ID, idZ } from "@/ontology/payload";
`import { type CrudeID, ... }`.

2024-08-12 19:16 UTC, Lham42 commented
This is a pretty large pr - can you provide more details on the primary changes you made in the pr description.

2024-08-13 16:39 UTC, emilbon99 commented on x/ts/src/kv/types.ts
> +export interface Pair<K = string, V = string> {
It's clunky to use generics with `z.infer`

2024-08-13 16:49 UTC, emilbon99 commented on synnax/pkg/ranger/kv.go
> +func (k KVPair) GorpKey() string { return k.Range.String() + "<--->" + k.Key }
To do efficient lookups on the key-value store for a particular range. `<-->` is used as a very unique separator that is unlikely to occur in the key. A value like `-` or `:` could appear in the key.

2024-08-13 16:53 UTC, emilbon99 commented on synnax/pkg/ranger/writer.go
> +	return err
Values automatically get initialized to the zero value for their type in Go, so this would return nil.

2024-08-13 17:26 UTC, emilbon99 commented on x/ts/src/observe/observe.ts
> +export const wrapWithTransform = <I, O>(
Turns out this was dead code. Removed.

2024-08-13 21:20 UTC, Lham42 commented
ts test failing

2024-08-14 03:03 UTC, Lham42 requested changes
Check API/typescript failing

2024-08-14 03:07 UTC, emilbon99 commented on synnax/pkg/distribution/ontology/ontology.go
> +	// types from the resource with the given Task. If the resource does not exist, or if
Resolved

2024-08-14 17:34 UTC, pjdotson commented
It looks like there is some functionality that needs to be improved + documentation added.
 
 **Channel Aliases**
 - Channel aliases do not propagate from parent range to descendant ranges.
 
 **Range Tab**
 - Cannot view + edit channel aliases in the range tab (these should also probably show if they are inherited from a parent).
 - Add a button to open the range on a new plot / active plot
 - "Sub-range of {parent_range}" will not automatically re-render when the name of the parent range changes.
 
 **Resources Toolbar**
 - Context menu should have these options added:
   - Create child range of {range_name}
 
 **Ranges Toolbar**
 - Context menu should have these options added:
   - Add {range_name} to new plot
   - Add {range_name} to active plot
   - Create child range from {range_name}
   - Set as active range
   
 **Deep linking**
- Deep linking should now open the range tab instead of adding the range to a plot

**Documentation**
- typescript client: ranges
- python client: ranges
- console: ranges

Switching active ranges when toggling the range window seems to be inconsistent behavior.
- When I have one window w/ two tab, range 1 and range 2, toggling the tabs switches them.
- When I have a mosaic view w/ range 1 and range 2 on the left and right side of the screen, toggling the active tab does _not_ change the active range.
I think we should change the active range when the active tab changes.

Changing the name of the range does not change the name of the range tab at the top. We all should be able to edit the name from their like with schematics and line plots.

2024-08-16 00:44 UTC, pjdotson commented
@emilbon99 New comments:

- [ ] Make sure channel aliases properly propagate down to child ranges
- [ ] Change the "add to active plot" context menu text to read "Add to {active_plot_name} in
  - [ ] resources toolbar
  - [ ] ranges toolbar

2024-08-16 15:22 UTC, pjdotson approved these changes

2024-08-16 16:38 UTC, Lham42 approved these changes
LGTM

2024-08-16 17:37 UTC, merged