Sy 1117 force bazel to not cache test results for cpp client test
synnaxlabs/synnax pull request #786
Opened 2024-08-24 18:36 UTC by LeonLiur

# Fix Pull Request Template

## Key Information

- **Linear Issue**: [SY-1117]()

## Description

Currently the workflow in the CPP client caches test results when there are no changes to the client or its tests – this disables us from detecting errors with the client caused by changes in the server.

## Basic Readiness Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added sufficient regression tests to cover the changes to CI.
- [ ] I have added relevant tests to cover the changes or exposing bugs.
- [ ] I have verified code coverage targets are met.

## Additional Notes
- [ ] These changes deal with concurrency.
- [ ] These changes affect UI.

## Manual QA Additions

- [ ] I have updated the [Release Candidate](/.github/PULL_REQUEST_TEMPLATE/rc.md) template
  with necessary manual QA steps to test my change.

## Reviewer Checklist
- [ ] Sufficient test coverage of new additions.
- [ ] Verified all steps in readiness checklists.
- [ ] UI changes have been tested.
- [ ] style and formatting is consistent.
- [ ] Reviewed any relevant changes to concurrent code for safety. 
- [ ] Sufficient comments and clarity of code.

2024-08-24 22:13 UTC, Lham42 requested changes

2024-08-24 22:13 UTC, Lham42 commented on console/release-spec.json
this change shouldnt be here if u are merging to main

2024-08-25 01:30 UTC, LeonLiur commented on console/release-spec.json
Addressed

2024-08-28 03:25 UTC, Lham42 approved these changes

2024-08-28 03:26 UTC, merged