[docs/site] - updated documentation site to include troubleshoting links
synnaxlabs/synnax pull request #799
Opened 2024-08-30 23:59 UTC by emilbon99

# Feature Pull Request Template

## Key Information

- **Linear Issue**: [SY-####]()

## Description

Maximum 2-3 sentence description describing the changes.

## Basic Readiness Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have added relevant tests to cover the changes to CI.
- [ ] I have updated user facing documentation accordingly.
- [ ] I have verified code coverage targets are met.

## Migrations

- [ ] Console - I have ensured that previous versions of stored data structures are 
properly migrated to new formats.
- [ ] Server - I have ensured that previous versions of stored data structures are 
properly migrated to new formats.

##  Additional Notes
- [ ] These changes deal with concurrency.
- [ ] These changes affect UI.

## Manual QA Additions

- [ ] I have updated the [Release Candidate](/.github/PULL_REQUEST_TEMPLATE/rc.md) template
with necessary manual QA steps to test my change.

## Breaking Changes

Please list any breaking changes to public or internal packages.

## Reviwer Checklist
- [ ] Sufficient test coverage of new additions.
- [ ] Verified all steps in the Readiness checklists.
- [ ] UI changes have been tested.
- [ ] Style and formatting is consistent.
- [ ] Reviewed any relevant changes to concurrent code for safety. 
- [ ] Sufficient comments and clarity of code.
- [ ] Any additional documentation necessary for feature is provided and has been reviewed for clarity.

2024-08-31 14:13 UTC, Lham42 commented
Update title and pr description

2024-08-31 19:00 UTC, Lham42 commented
Add to the pr description - do we check the just major and minor or also the patch version?

2024-08-31 19:05 UTC, emilbon99 commented
@Lham42 Updated

2024-09-01 03:27 UTC, Lham42 requested changes

2024-09-02 15:21 UTC, Lham42 commented
Also Client API test failing - is this expected and if so make it explicit a change to the API is being made in the PR description.

2024-09-02 15:24 UTC, pjdotson requested changes

2024-09-02 15:24 UTC, pjdotson commented on client/ts/src/connection/checker.ts
> +          Synnax cluster node version is too old for client version ${this.clientVersion}.
Can you consolidate these error statements into one statement somewhere that accepts arguments for old / new and the versions? It's pretty hard to follow the logic of so many nested if-else statements and that would make it easier.

2024-09-02 15:24 UTC, pjdotson commented on client/ts/src/connection/connection.spec.ts
> +    it("should adjust state if the server is too old", async () => {
Add a test for where the server is too new as well.

2024-09-02 15:24 UTC, pjdotson commented on pluto/src/synnax/Provider.tsx
> +        add({
Rename this `addStatus` to match the rest of the codebase.

2024-09-02 15:24 UTC, pjdotson commented on pluto/src/synnax/Provider.tsx
> +        Compatibility issues may arise.
Personally I think we should put long strings on one line, but I don't know if there is a convention followed in the rest of the codebase.

2024-09-02 15:24 UTC, pjdotson commented on pluto/src/synnax/Provider.tsx
> +          description = `Cluster version is older than client version ${connectivity.clientVersion}. Compatibility issues may arise. `;
You could probably also make these strings a function that you pass older / newer / versions into, but I think this is easier to read than the client checker so you don't have to.

2024-09-02 15:24 UTC, pjdotson commented on docs/site/src/pages/reference/typescript-client/troubleshooting.mdx
> +or downgrade to a matching version of the client.
End this line with a colon.

2024-09-02 15:24 UTC, pjdotson commented on docs/site/src/pages/reference/typescript-client/troubleshooting.mdx
> +resolve this issue, we recommend upgrading the Synnax TypeScript client.
End this line with a colon.

2024-09-02 15:24 UTC, pjdotson commented on console/src/hardware/device/external.ts
> +import { notificationAdapter } from "@/version/Updater";
You should be import `Version` from "@/version" instead of importing one file in the package.

2024-09-02 15:24 UTC, pjdotson commented on console/src/cluster/notification.tsx
> +  if (status.data.type !== "serverVersionMismatch") return null;
Could we change the string `"serverVersionMismatch"` to a `const` that gets exported from Pluto and imported here?

2024-09-02 15:24 UTC, pjdotson commented on console/src/cluster/notification.tsx
> +  const oldSever = status.data.oldServer as boolean;
typo in `oldSever`

2024-09-02 19:37 UTC, merged