Sy 1337 python client support for opc ua
synnaxlabs/synnax pull request #886
Opened 2024-10-28 16:31 UTC by emilbon99

# Feature Pull Request Template

## Key Information

- **Linear Issue**: [SY-#](https://linear.app/synnax/issue/)

## Description

Please write a short (2-3 sentence) description describing the changes.

## Basic Readiness

- [ ] I have performed a self-review of my code.
- [ ] I have added relevant tests to cover the changes to CI.
- [ ] I have needed QA steps to the [release
      candidate](/.github/PULL_REQUEST_TEMPLATE/rc.md) template that cover these changes.
- [ ] I have updated in-code documentation to reflect the changes.
- [ ] I have updated user-facing documentation to reflect the changes.

## Backwards Compatibility

The following makes sure that this feature does not break backwards compatability.

### Data Structures

- [ ] Server - I have ensured that previous versions of stored data structures are
      properly migrated to new formats.
- [ ] Console - I have ensured that previous versions of stored data structures are
      properly migrated to new formats.

### API Changes

- [ ] Server - The server API is backwards-compatible
- The following client APIs are backwards-compatible:
  - [ ] C++
  - [ ] TypeScript
  - [ ] Python

### Breaking Changes

If anything in this section is not true, please list all breaking changes.

2024-10-31 18:43 UTC, pjdotson requested changes
Still need to make sure it actually works on OPC server, but added a few comments / requests.

2024-10-31 18:43 UTC, pjdotson commented on client/py/examples/opcua/read_task.py
> +frame.to_df().to_csv("opcua_read_result.csv")
Probably better for this example to just pop up the plots using pyplot right?

2024-10-31 18:43 UTC, pjdotson commented on client/py/synnax/hardware/opcua/types.py
> +    def run(self, timeout: float | TimeSpan = 5):
You need to explain what `timeout` does in a docstring for `start`, `stop`, and `run`.

2024-10-31 18:43 UTC, pjdotson commented on client/py/examples/opcua/__init__.py
Do we need this file?

2024-10-31 18:43 UTC, pjdotson commented on client/py/examples/opcua/read_task.py
> +tsk = opcua.ReadTask(
I think it would be good to put an example timeout here too, just so that someone could follow along.

2024-10-31 18:43 UTC, pjdotson commented on client/py/synnax/hardware/ni/types.py
You should add docstrings to every function that accepts `timeout` to explain what that does.

2024-10-31 18:43 UTC, pjdotson commented on client/py/synnax/hardware/task/client.py
> +                    print(state, key)
Should we really be using `print` here?

2024-11-05 16:52 UTC, emilbon99 commented on client/py/synnax/hardware/task/client.py
> +                    print(state, key)
No

2024-11-05 23:17 UTC, pjdotson commented
@emilbon99 It looks like none of my comments were actually addressed even though they are marked as resolved.

2024-11-05 23:24 UTC, emilbon99 commented
Are you sure you refreshed? I addressed all of them example for the CSV to plot one

2024-11-05 23:24 UTC, emilbon99 commented
Oh, I also missed the NI docs. Will add those

2024-11-05 23:50 UTC, pjdotson commented
> Are you sure you refreshed? I addressed all of them example for the CSV to plot one

My bad, I didn't have my view set to latest commits.

2024-11-05 23:50 UTC, pjdotson approved these changes

2024-11-06 13:32 UTC, merged