Sy 1604 clickable manual valves
synnaxlabs/synnax pull request #943
Opened 2024-11-26 21:03 UTC by Lham42

# Issue Pull Request

## Key Information

- **Linear Issue**: [SY-####](https://linear.app/synnax/issue/)

## Description

## Basic Readiness

- [ ] I have performed a self-review of my code.
- [ ] I have added relevant tests to cover the changes to CI.
- [ ] I have added needed QA steps to the [release candidate](/synnaxlabs/synnax/blob/main/.github/PULL_REQUEST_TEMPLATE/rc.md) template that cover these changes.
- [ ] I have updated in-code documentation to reflect the changes.
- [ ] I have updated user-facing documentation to reflect the changes.

## Backwards Compatibility

### Data Structures

I have ensured that previous versions of stored data structures are properly migrated to new formats in the following projects:

- [ ] Server
- [ ] Console

### API Changes

The following projects have backwards-compatible APIs:

- [ ] Python Client
- [ ] Server
- [ ] TypeScript Client

### Breaking Changes

2024-11-26 21:21 UTC, emilbon99 reviewed
I don't think that all non-interactive symbols should be made interactive by default. The best way to approach this is to add a "dummy" parameter to all toggleable and non-toggleable symbols. If "dummy" is enabled, _then allow toggle_.

2024-11-26 21:21 UTC, emilbon99 commented on pluto/src/vis/schematic/Symbols.tsx
> +    const handleClick = () => {
This code has a lot of duplication. Create a relevant HOC.

2024-11-26 21:21 UTC, emilbon99 requested changes
See my comments

2024-11-26 23:04 UTC, pjdotson commented
Did you check that this wont break elements on old schematics that don't have the `enabled` prop?

2024-11-26 23:34 UTC, Lham42 commented
> Did you check that this wont break elements on old schematics that don't have the `enabled` prop?

not yet

2024-11-27 15:01 UTC, pjdotson commented on pluto/src/vis/schematic/registry.ts
> +    enabled: false,
Move these into a `ZERO_DUMMY_TOGGLE_PROPS` constant and use spread notation.

2024-11-27 15:04 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +};
Can revert all of this back

2024-11-27 15:05 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +  onClick?: MouseEventHandler<HTMLButtonElement>;
`enabled` and `onClick` already exist on `ToggleProps`, right?

2024-11-27 15:05 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +  onClick,
Don't need the `onClick` here, the spread in `...props` covers it

2024-11-27 15:07 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +      <HandleBoundary orientation={orientation}>
Why did you change the width, height, dimensions, etc.?

2024-11-27 15:07 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +  onClick?: MouseEventHandler<HTMLButtonElement>;
Don't need to extend these, see above

2024-11-27 15:08 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +  onClick,
don't need the `onClick`, see above

2024-11-27 15:08 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +    onClick={onClick}
Can remove the `onClick`, covered in `...props`

2024-11-27 15:08 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +  onClick?: MouseEventHandler<HTMLButtonElement>;
see above

2024-11-27 15:08 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +  onClick,
see above

2024-11-27 15:08 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +    onClick={onClick}
see above

2024-11-27 15:08 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +  onClick?: MouseEventHandler<HTMLButtonElement>;
see above

2024-11-27 15:08 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +  onClick,
see above

2024-11-27 15:09 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +    onClick={onClick}
see above

2024-11-27 15:09 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +        top={97.0278}
Why were the dimensions here changed?

2024-11-27 15:09 UTC, pjdotson commented on pluto/src/vis/schematic/primitives/Primitives.tsx
> +  onClick?: MouseEventHandler<HTMLButtonElement>;
see above

2024-11-27 18:04 UTC, merged