SY-1611: Bring Back Line Plot Annotation Tool
synnaxlabs/synnax pull request #951
Opened 2024-12-01 22:21 UTC by pjdotson

# Issue Pull Request

## Key Information

- **Linear Issue**: [SY-1611](https://linear.app/synnax/issue/SY-1611/bring-back-annotation-tool)

## Description

Added the rules annotations back to the line plot visualization. Refactored some code to improve readability. Add a median to the `x/ts/bounds`. Couple QOL improvements to annotations (scrolling, better preset rules).

## Basic Readiness

- [x] I have performed a self-review of my code.
- [x] I have added relevant tests to cover the changes to CI.
- [x] I have added needed QA steps to the [release candidate](/synnaxlabs/synnax/blob/main/.github/PULL_REQUEST_TEMPLATE/rc.md) template that cover these changes.
- [x] I have updated in-code documentation to reflect the changes.
- [x] I have updated user-facing documentation to reflect the changes.

## Backwards Compatibility

### Data Structures

I have ensured that previous versions of stored data structures are properly migrated to new formats in the following projects:

- [x] Server
- [x] Console

### API Changes

The following projects have backwards-compatible APIs:

- [x] Python Client
- [x] Server
- [x] TypeScript Client

### Breaking Changes

2024-12-03 00:00 UTC, emilbon99 requested changes
![Screenshot 2024-12-02 at 3 57 17 PM](https://github.com/user-attachments/assets/5cb68555-400e-4407-8a72-7d1a317a4fe2)

Double clicking to edit the label on the rule does not work

2024-12-03 00:00 UTC, emilbon99 commented on x/ts/src/spatial/bounds/bounds.ts
> +export const median = (a: Crude): number => {
This seems more like a mean than a median

2024-12-06 18:44 UTC, emilbon99 reviewed
![Uploading Screenshot 2024-12-06 at 10.43.14 AM.png…]()

2024-12-06 18:44 UTC, emilbon99 commented
![Screenshot 2024-12-06 at 10 43 14 AM](https://github.com/user-attachments/assets/606a9bb3-7520-4639-8a0a-cff8e3f33d66)

2024-12-06 23:48 UTC, pjdotson commented
> ![Screenshot 2024-12-06 at 10 43 14 AM](https://private-user-images.githubusercontent.com/56323762/393368199-606a9bb3-7520-4639-8a0a-cff8e3f33d66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Mjg5NzEsIm5iZiI6MTczMzUyODY3MSwicGF0aCI6Ii81NjMyMzc2Mi8zOTMzNjgxOTktNjA2YTliYjMtNzUyMC00NjM5LThhMGEtY2ZmOGUzZjMzZDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDIzNDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YWYxYWVlOGQ4NjliMzk3YWFmNWI2ODk2ZjFiMjBjZjE3MmQxZmFkYTRlNGQwYzJhMmNiMjU1ZGQzNzkwYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NxgUs5OKrfJx2LRe28JwraHiBXbNSZ03uSZYTb5OkTU)

@emilbon99 I can't get the issues with the reseting position and rounding to replicate.

2024-12-15 00:17 UTC, merged